name: INTERWORD
favicon: null
layout_spectrum: 0.62644
typography_spectrum: 0.015093377092853189
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#356680'
    - '#808080'
    - '#bcbcbc'
    - '#9e9e9e'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.9265466860961169
purpose: []
