name: INTERWORD
favicon: null
layout_spectrum: 0.46478864713571966
typography_spectrum: 0.015093377092853189
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8863836019299924
  lightness: 0.8817934768740088
  saturation: 0.19875181885436177
  rhythmicContrast: 0.9265466860961169
purpose: []
